services:
  mirakurun:
    image: chinachu/mirakurun:3.8.0
    cap_add:
      - SYS_ADMIN
      - SYS_NICE
    environment:
      TZ: Asia/Tokyo
      DOCKER_NETWORK: host
      # LOG_LEVEL: "3"
      # DEBUG: "true"
    network_mode: host
    ports:
      - 40772:40772
      - 9229:9229
    devices:
      - /dev/bus:/dev/bus
      - /dev/dvb:/dev/dvb
    volumes:
      - type: bind
        source: /opt/mirakurun/run/
        target: /var/run/
      - type: bind
        source: /opt/mirakurun/opt/
        target: /opt/
      - type: bind
        source: /opt/mirakurun/config/
        target: /app-config/
      - type: bind
        source: /opt/mirakurun/data/
        target: /app-data/
    restart: always
    logging:
      driver: json-file
      options:
        max-file: "1"
        max-size: 10m

  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    network_mode: host
    ports:
      - 8080:8080
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    restart: always
    logging:
      driver: json-file
      options:
        max-file: "1"
        max-size: 10m

  newrelic:
    image: newrelic/infrastructure:latest
    cap_add:
      - SYS_PTRACE
    environment:
      TZ: Asia/Tokyo
      DOCKER_NETWORK: host
      NRIA_LICENSE_KEY: ${NRIA_LICENSE_KEY}
    network_mode: host
    volumes:
      - type: bind
        source: /
        target: /host
        read_only: true
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
      - type: bind
        source: ./newrelic/newrelic-infra
        target: /etc/newrelic-infra
    restart: always
    logging:
      driver: json-file
      options:
        max-file: "1"
        max-size: 10m
