services:
  mirakurun:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    image: chinachu/mirakurun:latest
    cap_add:
      - SYS_ADMIN
      - SYS_NICE
    environment:
      TZ: Asia/Tokyo
      # LOG_LEVEL: "3"
      # DEBUG: "true"
    ports:
      - ${MIRAKURUN_ADMIN_PORT:-40772}:40772
      - ${MIRAKURUN_PORT:-9229}:9229
    devices:
      - /dev/bus:/dev/bus
      - /dev/dvb:/dev/dvb
    volumes:
      - /usr/local/mirakurun/run/:/var/run/
      - /usr/local/mirakurun/opt/:/opt/
      - /usr/local/mirakurun/config/:/app-config/
      - /usr/local/mirakurun/data/:/app-data/
    restart: always
    logging:
      driver: json-file
      options:
        max-file: "1"
        max-size: 10m

  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - ${NGINX_CONTAINER_PORT:-8000}:80
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
