version: '3'

tasks:
  default:
    deps:
      - help

  help:
    desc: "ヘルプを表示する"
    cmd: task --list --sort none

  #
  # 初期化系
  #
  init:
    desc: "Dockerコンテナを初期設定する"
    cmds:
      - task: dotenv
      - task: pull
      - task: build

  dotenv:
    desc: ".envファイルを作成する"
    cmd: test -f .env || cp .env.example .env

  #
  # コンテナ操作系
  #
  build:
    desc: "Dockerイメージをビルドする"
    cmd: docker compose build {{.CLI_ARGS}}

  pull:
    desc: "Dockerイメージを取得ビルドする"
    cmd: docker compose pull {{.CLI_ARGS}}

  ps:
    desc: "Dockerコンテナの状態を表示する"
    cmd: docker compose ps {{.CLI_ARGS}}

  up:
    desc: "Dockerコンテナを起動する"
    cmd: docker compose up -d {{.CLI_ARGS}}

  down:
    desc: "Dockerコンテナを停止する"
    cmd: docker compose down {{.CLI_ARGS}}

  restart:
    desc: "Dockerコンテナを再起動する"
    cmd: docker compose restart {{.CLI_ARGS}}

  log:
    desc: "Dockerコンテナのログを表示する"
    cmd: docker compose logs {{.CLI_ARGS}}

  logs:
    desc: "Dockerコンテナのログを表示する (-fオプション付き)"
    cmd: docker compose logs -f {{.CLI_ARGS}}

  sh:epgstation:
    desc: "EPGStationのコンテナのシェルに入る"
    cmd: docker compose exec epgstation sh {{.CLI_ARGS}}

  mysql:
    desc: "MySQLにログイン"
    cmd: docker compose exec mysql mysql -u epgstation_user -pepgstation_passwd epgstation {{.CLI_ARGS}}

  #
  # バックアップ系
  #
  backup:
    desc: "各サービスをバックアップする"
    cmds:
      - task: backup:epgstation

  backup:epgstation:
    desc: "EPGStationをバックアップする"
    cmd: docker compose run --rm -it epgstation run backup /backup/epgstation-db.json
