name: Docker Compose build

on:
  pull_request:
    paths:
      - "docker/**"
      - "compose.yaml"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Task
        uses: arduino/setup-task@v2

      - name: Check task build
        run: task build
