name: Docker Compose build

on:
  pull_request:
    paths:
      - "docker/**"
      - "compose.yaml"

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      compose: ${{ steps.filter.outputs.compose }}
      epgstation: ${{ steps.filter.outputs.epgstation }}
      nginx: ${{ steps.filter.outputs.nginx }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          token: ""
          filters: |
            compose:
              - "compose.yaml"
            epgstation:
              - "docker/epgstation/**"
            nginx:
              - "docker/nginx/**"

  compose:
    runs-on: ubuntu-latest
    needs:
      - changes
    if: needs.changes.outputs.compose == 'true'
    steps:
      - uses: actions/checkout@v4
      - run: docker compose config --quiet
      - run: docker compose pull --dry-run

  epgstation:
    runs-on: ubuntu-latest
    needs:
      - changes
    if: needs.changes.outputs.epgstation == 'true'
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - name: Build EPGStation
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/epgstation/Dockerfile
          cache-from: type=gha
          cache-to: type=gha,mode=max

  nginx:
    runs-on: ubuntu-latest
    needs:
      - changes
    if: needs.changes.outputs.nginx == 'true'
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - name: Build Nginx
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/nginx/Dockerfile
          cache-from: type=gha
          cache-to: type=gha,mode=max
